### ISSUE TITLE
Server error when querying relatedness for the empty string

### ISSUE THREAD

**Issue by rspeer** [commonsense/conceptnet5#190] opened 2018-04-17 17:30 UTC
Sentry reports an Internal Server Error when querying `http://api.conceptnet.io/related/c/zh/`:

```
IndexError: list index out of range
  File "flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/_compat.py", line 33, in reraise
    raise value
  File "flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "flask_limiter/extension.py", line 544, in __inner
    return obj(*a, **k)
  File "conceptnet_web/api.py", line 125, in query_top_related
    results = responses.query_related(uri, filter=filter, limit=limit)
  File "conceptnet_web/responses.py", line 209, in query_related
    found = VECTORS.similar_terms(query, filter=filter, limit=limit)
  File "conceptnet5/vectors/query.py", line 233, in similar_terms
    vec = self.get_vector(query)
  File "conceptnet5/vectors/query.py", line 214, in get_vector
    vec = self.expanded_vector(terms, include_neighbors=include_neighbors)
  File "conceptnet5/vectors/query.py", line 183, in expanded_vector
    self.expand_terms(terms, limit_per_term, include_neighbors)
  File "conceptnet5/vectors/query.py", line 147, in expand_terms
    englishified = '/c/en/' + split_uri(term)[2]
```

**Comment by luminoso-beaudoin** [comment] 2018-04-17 20:05
The immediate cause of the problem is the final line in the traceback shown (which implements the OOV strategy of replacing nominally non-english concepts with the same word in english); attempting to take the third entry of the output of split_uri raises an exception when the uri (like '/c/zh/') has only two parts.  I've fixed that (on a branch). It isn't clear to me if we want to do more than that; with this fix both querying for things related to '/c/en/' and '/c/zh/' will return (quite a few) results - is that sensible?

**Comment by rspeer** [comment] 2018-04-17 20:11
It doesn't make sense to ask for similarity to an entire language, so returning no results would be fine.

**Comment by luminoso-beaudoin** [comment] 2018-04-20 17:44
Fixed in (merged) PR 189.

**Closed by luminoso-beaudoin** 2018-04-20 17:44 UTC
