### ISSUE TITLE
Docker image build failed due to database creation error "mkdir: cannot create directory ‘/data/conceptnet/psql’: Permission denied"

### ISSUE THREAD

**Issue by qiaochen** [commonsense/conceptnet5#172] opened 2018-03-10 05:59 UTC
Hey there!

I was following the docker installation [guide](https://github.com/commonsense/conceptnet5/wiki/Docker) but failed with permission error when creating the database.

Would you please help me figure it out please?

![image](https://user-images.githubusercontent.com/5159030/37238856-8046221c-246a-11e8-8fb8-5132f3d530ec.png)

**Comment by qiaochen** [comment] 2018-03-10 06:45
Seems user has been changed to "postgres", as the output of whoami is:
db_1   | postgres

**Comment by rspeer** [comment] 2018-03-12 15:38
I thought that's what the user was supposed to be, but the fact that this stopped working either has something to do with your Docker volumes, or it's because the "postgres" package changed under us again.

Do you have a suggested fix? Debugging Docker is not where I want to be spending my time working on ConceptNet.

**Comment by rspeer** [comment] 2018-04-10 22:46
I believe that #186 is a duplicate of this.

Fixing it will require someone who uses Docker (I don't anymore) to track down why the permissions of `/data/conceptnet/psql` are wrong.

**Comment by rspeer** [comment] 2018-05-14 21:09
Seems clear that this bug will not be resolved, and that you might as well use ConceptNet 5.6 instead.

**Closed by rspeer** 2018-05-14 21:09 UTC
